### ISSUE TITLE
correct file format for copy-number segments

### ISSUE THREAD

**Issue by seedgeorge** [AAlhendi1707/PhylogicNDT_Docker#1]
Hi, 
Can you confirm the format for the copy-number segmentation file? 
I have a table with the following columns in a tab-separated format.

`ID\tChromosome\tStart_position\tEnd_Position\tA1_CN\tA2_CN
`
However, PhylogicNDT does not recognise it. 
All help appreciated,
Kind regards.

**Comment by AAlhendi1707** [comment]
Please refer to [PhylogicNDT GitHub repository](https://github.com/broadinstitute/PhylogicNDT) for details on input requirements and guidelines for interpreting the results
